### PR TITLE
WIP: Find data-layer/action creators and their action types

### PR DESCRIPTION
**Pull request by timdream**
This branch contains two transforms that could

1. See if a given file is a data-type handler or an action creator
2. Extract action types it handles or sets.
3. `console.log` the output.

I have a shell script 😵 that combines the output into JSON files and generates a list of files to do the final transforms to move data-layer handlers imports to action creators. At least it's the idea for now.

See https://github.com/timdream/wp-calypso/commit/441c4a2094b77b7b963777f77ebc8d242d64b81c

I am not entirely sure these "transforms" should be in this repo. They are not actually transforms to be exact :-/ Having them here doesn't make them testable either. Let me know where is the right place to put this.

### CODE REVIEW

**Comment by samouri** [comment]
I think this would become testable if instead of just logging the output, you also returned it.

So for example, the last line of `transforms/get-action-creators-action-types.js` would become:

```js
const output = JSON.stringify({ file: file.path, types: actionTypes });
console.log(output);
return output;
```

**Comment by timdream** [comment]
@samouri Unfortunately I cannot output the object because jscodeshift will write it into the file.

**Comment by samouri** [comment]
>  jscodeshift will write it into the file.

@timdream: thats fine. You don't plan on "running" this for real anyway, you just care about the output.  Doing a dry-run is the equivalent of logging the output except it'll be easily testable.

**Comment by timdream** [comment]
This is too fragile to be usable, closing.

**Pull request closed without merging**
